# Generated by Django 4.2.16 on 2025-11-10 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('archivo', models.FileField(null=True, upload_to='certificaciones/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificaciones', to='Usuario.trabajador')),
            ],
        ),
    ]
