# Generated by Django 5.2.5 on 2025-10-14 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_region', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contrato', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Contrato',
                'verbose_name_plural': 'Tipos de Contrato',
            },
        ),
        migrations.CreateModel(
            name='OfertaEmpleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título de la Oferta')),
                ('descripcion', models.TextField(verbose_name='Descripción del Puesto')),
                ('estado', models.CharField(choices=[('AB', 'Abierta'), ('CE', 'Cerrada'), ('PA', 'Pausada')], default='AB', max_length=2, verbose_name='Estado')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Publicación')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresa.empresa', verbose_name='Empresa')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Oferta_Empleo.region', verbose_name='Región')),
                ('tipo_contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Oferta_Empleo.tipo_contrato', verbose_name='Tipo de Contrato')),
            ],
            options={
                'verbose_name': 'Oferta de Empleo',
                'verbose_name_plural': 'Ofertas de Empleo',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
