# Generated by Django 5.0.6 on 2025-12-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oferta_Empleo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertaempleo',
            name='direccion_texto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ofertaempleo',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ofertaempleo',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
