# Generated by Django 5.0.6 on 2025-12-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oferta_Empleo', '0002_ofertaempleo_direccion_texto_ofertaempleo_latitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertaempleo',
            name='es_externa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ofertaempleo',
            name='id_externo_adzuna',
            field=models.CharField(blank=True, help_text='ID único de la oferta en Adzuna', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ofertaempleo',
            name='url_postulacion_externa',
            field=models.URLField(blank=True, help_text='Link para postular si es externa', max_length=500, null=True),
        ),
    ]
