# Generated by Django 5.0.6 on 2025-12-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oferta_Empleo', '0003_ofertaempleo_es_externa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertaempleo',
            name='es_externa',
            field=models.BooleanField(default=False, help_text='Indica si la oferta viene de una API externa'),
        ),
        migrations.AlterField(
            model_name='ofertaempleo',
            name='id_externo_adzuna',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ofertaempleo',
            name='url_postulacion_externa',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
