# Generated by Django 5.2.5 on 2025-10-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título del Curso')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('duracion_horas', models.PositiveIntegerField(blank=True, help_text='Duración total estimada del curso en horas.', null=True, verbose_name='Duración en Horas')),
                ('url_contenido', models.URLField(blank=True, help_text='URL externa donde se aloja el material del curso.', max_length=2083, verbose_name='Enlace al Contenido')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['titulo'],
            },
        ),
    ]
