# Generated by Django 4.2.16 on 2025-12-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='por_que_elegirla',
            field=models.TextField(blank=True, help_text='Una razón por línea.', verbose_name='Por qué elegirla'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='roles_clave',
            field=models.TextField(blank=True, help_text='Separados por coma, ej: Full-Stack Developer, Data Analyst', verbose_name='Roles clave'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tamano_rango',
            field=models.CharField(blank=True, help_text='Ej: 51–200 personas', max_length=50, verbose_name='Tamaño'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ubicacion_texto',
            field=models.CharField(blank=True, help_text='Ej: Santiago, RM', max_length=255, verbose_name='Ubicación'),
        ),
    ]
