# Generated by Django 5.0.6

from django.db import migrations

# Lista de industrias a agregar
INDUSTRIAS = [
    "Agricultura y Pesca",
    "Alimentos y Bebidas",
    "Construcción e Inmobiliaria",
    "Consultoría y Servicios Profesionales",
    "Educación",
    "Energía y Recursos Naturales",
    "Entretenimiento y Medios",
    "Gobierno y Sector Público",
    "Manufactura",
    "Minería",
    "Organización sin fines de lucro",
    "Retail / Comercio Minorista",
    "Salud y Bienestar",
    "Servicios Financieros y Seguros",
    "Tecnología de la Información",
    "Transporte y Logística",
    "Turismo y Hotelería",
    "Otro",
]

def populate_industrias(apps, schema_editor):
    """
    Crea las instancias del modelo Industria a partir de la lista.
    """
    Industria = apps.get_model('Empresa', 'Industria')
    for nombre in INDUSTRIAS:
        Industria.objects.get_or_create(nombre_industria=nombre)

class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0001_initial'), # Asegúrate que dependa de la migración inicial
    ]

    operations = [
        migrations.RunPython(populate_industrias),
    ]
