# Generated by Django 5.0.6 on 2025-12-01 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0002_populate_industrias'),
    ]

    operations = [
    ]
