# Generated by Django 5.0.6 on 2025-12-02 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0002_empresa_por_que_elegirla_empresa_roles_clave_and_more'),
        ('Empresa', '0003_populate_industrias'),
    ]

    operations = [
    ]
